### ISSUE TITLE
boost_fetch very slow on repeated builds

### ISSUE THREAD

**Issue by HDembinski** [boostorg/mincmake#2]
I started to re-implement CMake Support in Boost::histogram, using mincmake and Boost conforming CMake configuration. Histogram depends directly on 8 Boost libraries, but indirectly on 29. I currently use boost_fetch, but it takes very long to fetch 29 libraries every time. Is there a way to speed this up? I think once a dependency was fetched, it shouldn't be re-fetched unless the user deletes the dependency directory.

**Comment by pdimov** [comment]
At the moment I use the form of `FetchContent_Populate` which re-downloads each time. I should probably switch to using `FetchContent_Declare` and then `FetchContent_Populate(name)`, or perhaps `FetchContent_MakeAvailable`.

**Comment by pdimov** [comment]
I tried splitting the `FetchContent_Populate` call as per the documentation of FetchContent, but each `cmake` reconfiguration still redownloads the libraries (w/ CMake 3.12).

**Comment by HDembinski** [comment]
Thank you, I am happy with the version in develop.

It is like you say, but the reconfigure is still faster for some reason that is not entirely clear to me.

The version with _Declare and _Populate has the advantage that FETCHCONTENT_FULLY_DISCONNECTED and FETCHCONTENT_UPDATES_DISCONNECTED are respected:

https://cmake.org/cmake/help/v3.11/module/FetchContent.html?highlight=fetchcontent

> [FetchContent_Populate with options] has a number of key differences to that where only <name> is provided:
>
> * All required population details are assumed to have been provided directly in the call to FetchContent_Populate(). Any saved details for <name> are ignored.
> * No check is made for whether content for <name> has already been populated.
> *  No global property is set to record that the population has occurred.
> *  No global properties record the source or binary directories used for the populated content.
> *  The FETCHCONTENT_FULLY_DISCONNECTED and FETCHCONTENT_UPDATES_DISCONNECTED cache variables are ignored.
